# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
resource "null_resource" "null2" {
}


terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region = "us-east-1"
}
